terrain:
  obj_path: "assets/Terrain/terrain_type/Mountain/Mountain_5Peaks_200Height_0Seed_debug.obj"
  obj_scale: [0.25,0.25,0.25]
  obj_pos: "center" #corner
  texture_path: "assets/textures/rock.jpg"
  texture_scale: [0.009, 0.009]

atmosphere:
  time:
    day_length: 24
    time: "08:00:00"
  sky:
    obj_path: "models/misc/sphere"
    obj_scale: 10000
    obj_pos: "center"
    color_day: [0.53, 0.81, 0.92, 1.0]
    color_twilight: [0.95, 0.45, 0.20, 1.0]
    color_night: [0.1, 0.1, 0.1, 1.0]
    light_source:
      obj_path: "models/misc/sphere"
      obj_scale: 120
      distance: 5000
      color_temp: 5000
  clouds:
    obj_path: ""
    obj_scale: [1,1,1]
    obj_pos: "random"
    texture_path: ""
    texture_scale: []
  
static:
    trees:
      obj_path: ["assets/Terrain/terrain_features/quick_tree.bam"]
      obj_scale: [3,3,3]
      obj_number: [30]
      obj_orientation: [0,0,0]
      obj_pos: "random"
      texture_path: ["",""]
      color: ["",""]
    # rocks:
    #   obj_path: ""
    #   obj_scale: [1,1,1]
    #   obj_number: 10
    #   obj_orientation: [0,0,0]
    #   obj_pos: "random"
    #   texture_path: ""
    #   color: ""

dynamic:
  sun:
    obj_path: ""
    obj_scale: [1,1,1]
    obj_number: 1
    obj_orientation: [0,0,0]
    obj_pos: [0,90]
    obj_vel: []
    obj_vec_space: "cylinder"
    texture_path: ""
    color: ""
  clouds:
    obj_path: ["",""]
    obj_scale: [1,1,1]
    obj_number: 40
    obj_orientation: [0,0,0]
    obj_pos: "random"
    obj_vel: [10,0,0]
    obj_vec_space: "euclidean"
    texture_path: ["",""]
    color: ["",""]

agents:
  DummyAgent:
    name: "DummyAgent"
    config_path: "config\\agent\\dummy_agent.yaml"
    id: 1
  # BasicAgent:
    name: "BasicAgent"
    config_path: "config\\agent\\basic_agent.yaml"
    id: 2
  agent_with_camera:
    name: "AgentWithCamera"
    config_path: "config\\agent\\agent_with_camera.yaml"
    agent_id: 3
  target_drone:
    name: "ThermalTargetDrone"
    config_path: "config\\agent\\target_drone.yaml"
    agent_id: 4
