type: "dummy"
model: ""
sensor_id: 6967

model_configs:
  model: ".\\assets\\Agents\\Generic Quadcopter Drone.obj"
  position: [0, 0, 0]
  orientation:
  color:
  scale: 0.01
  model_orientation: [0, 0, 0]
  model_position: [0, 0, 0]
