%YAML 1.2
---
name:
id:

settings:
  velocity:
  angular_rates:
  mass:
  agent_id:
  thermal:
  tf:
  file_path:
  max_vel:

  
sensors:
  Boson640:
    type: "ir_camera"
    config_path: "config\\sensors\\flir_boson_640.yaml"
sound:
animation:

model_configs:
  model: ".\\assets\\Agents\\Generic Drone\\Generic Quadcopter Drone.obj"
  position: [-0, 10, 50]
  orientation:
  color: [0, 0, 255]
  scale: 0.1
  model_orientation: [0, 0, 0]
  model_position: [0, 0, -50]
